spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    user: ${DB_USERNAME}
    password: "password"
    schemas: public
    locations: db/migration
    baselineOnMigrate: true
  security:
    user:
      password: ${DB_PASSWORD}
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"

springdoc:
  api-docs:
    path : '/api-docs'
    swagger-ui:
      path: '/swagger-ui.html'


jwt.secret: "SecretJWTKey123"
jwt.expiration: 608500