spring:
  datasource:
    username: ${DB_USERNAME:POSTGRES}
    url: ${DB_URL:POSTGRES}
    password: ${DB_PASSWORD:POSTGRES}
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
  flyway:
    user: ${DB_USERNAME:POSTGRES}
    password: ${DB_PASSWORD:POSTGRES}
    schemas: public
    locations: db/migration
    baselineOnMigrate: true
  security:
    user:
      password: ${USER_PASSWORD:user}
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
springdoc:
  api-docs:
    path : '/api-docs'
    swagger-ui:
      path: '/swagger-ui.html'


jwt.secret: ${JWT_SECRET}
jwt.expiration: ${JWT_EXPIRATION}