spring:
  datasource:
    username: "postgres"
    url: "jdbc:postgresql://localhost:5432/password-manager"
    password: "password"
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
  flyway:
    user: "postgres"
    password: "password"
    schemas: public
    locations: db/migration
    baselineOnMigrate: true
  security:
    user:
      password: "password"
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
springdoc:
  api-docs:
    path : '/api-docs'
    swagger-ui:
      path: '/swagger-ui.html'


jwt.secret: "SecretJWTKey123"
jwt.expiration: 608500